version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      demo:
        patterns:
            - "*"
    reviewers:
      - "@TransferGo/sme"